### ISSUE TITLE
Better error message for forgotten password form

### ISSUE THREAD

**Issue by henrahmagix** [wildfoundry/dataplicity#4]
To me, "Email address invalid" says "you have input a malformed email", not "your email is not in our system so you haven't registered with it yet."

![image](https://cloud.githubusercontent.com/assets/1429026/12885108/1bb9603c-ce5b-11e5-8337-87d02ada3693.png)

**Comment by meshy** [comment]
Thanks for that -- you're absolutely right about the nature of the error. That email address hasn't been registered.

We're working on UX improvements at the moment, and will make sure to address that while we're there. `:)`

**Comment by henrahmagix** [comment]
Thanks!

**Comment by meshy** [comment]
Here you go, @henrahmagix! Hope this helps!

![screenshot from 2016-07-06 13-52-44](https://cloud.githubusercontent.com/assets/767671/16618372/f0b18892-4380-11e6-8b2a-fe2584d22d43.png)
